### ISSUE TITLE
val accuracy of the paper models

### ISSUE THREAD

**Issue by pratikm141** [leokarlin/LaSO#11]
Hi, can you kindly mention the val accuracies of the paper models that you obtained after training. For example I am at epoch 5 and the checkpoints show networks_base_model_4_val_acc=0.549.pth, networks_classifier_4_val_acc=0.549.pth, networks_setops_model_4_val_acc=0.549.pth files.

It will be very helpful as training for 50 epochs will take a very long time.

Thanks in advance.

**Comment by pratikm141** [comment]
@leokarlin   How to use these trained models because the setops models can only load paperSubModel, paperInterModel, and paperUnionModel separately, but these are not getting saved separately by the code.

**Comment by alfassy** [comment]
Hi, sorry for the delay, the expected results, are in the README of this repository.

**Comment by alfassy** [comment]
I assume that you are trying to use a different setops class then the one you used in training, I gave all of our classes so that people can continue and use everything we can offer.
The default one being used for training is "SetOpsResModule", this class is loading the state dictionary by default through the setup_model function which is in every train/ test script.
I hope this help, I will close this issue, feel free to open it if you have any follow up questions.
Again, sorry for the delay.
